# Generated by Django 5.1.2 on 2024-10-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio_comprado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
