# Generated by Django 5.1.2 on 2024-10-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_insumo_precio_comprado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_recepcion',
        ),
    ]
