# Generated by Django 5.1.2 on 2024-10-29 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_pedido_proveedor_pedido_usuario_and_more'),
        ('usuarios', '0003_alter_empleado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='recepcionpedido',
            name='recibido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado'),
        ),
    ]
