# Generated by Django 5.1.2 on 2024-10-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_total_monto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
