# Generated by Django 5.1.2 on 2024-10-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='usuario',
            new_name='user_name_venta',
        ),
    ]
