# Generated by Django 5.1.2 on 2024-11-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_itemventa_producto_precio_unidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemventa',
            old_name='tipo_pecio',
            new_name='tipo_precio',
        ),
    ]
