# Generated by Django 5.1.2 on 2024-10-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemventa',
            name='producto',
        ),
    ]
