# Generated by Django 5.1.2 on 2024-10-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_itemventa_producto'),
        ('ventas', '0002_remove_venta_items_itemventa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemVenta',
        ),
    ]
