# Generated by Django 5.1.2 on 2024-10-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.FloatField(),
        ),
    ]
