# Generated by Django 5.1.2 on 2024-10-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_delete_itemventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
