# Generated by Django 5.1.2 on 2024-11-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='isActive',
        ),
        migrations.AddField(
            model_name='producto',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
